//! Detecting generated files by their marker (RL-305b, SPEC §9.4, ADR 0014).
//!
//! # Why this is not a glob
//!
//! §9.4's default `ignore_globs` list ends with "generated-file markers", which is
//! not a path pattern. It means a marker *inside* the file — conventionally an
//! `@generated` line near the top, as Go, protobuf, Prettier and bazel all emit.
//! A generated file can live anywhere and be called anything, which is exactly why
//! the convention exists.
//!
//! Deciding it needs file content, so it happens after materialisation, where the
//! tree is already checked out and the read costs nothing extra.
//!
//! # A header, not a substring
//!
//! The marker is a header by convention, and matching it anywhere would suppress
//! any file that *documents* the convention — this module's own source would
//! qualify, as would a linter config listing the markers it recognises. So only
//! the first [`HEADER_LINES`] lines are considered.
//!
//! The read is bounded twice: by lines and by bytes. Generated files are routinely
//! megabytes — a single-line minified bundle has no line breaks at all — and
//! reading one in full to check its header would make a cheap test expensive
//! exactly where it matters most.
//!
//! # `DO NOT EDIT` alone is not enough
//!
//! It appears in hand-written files often enough to be dangerous: a config with a
//! "DO NOT EDIT below this line" divider is hand-written and worth reviewing.
//! Go's full form — `Code generated by … DO NOT EDIT.` — is specific because the
//! Go team had the same problem.

use std::collections::BTreeMap;
use std::io::Read;
use std::path::Path;

/// How many lines of a file are considered part of its header.
///
/// Forty is generous for a convention that puts the marker in the first few: a
/// licence block, a shebang and a couple of imports can precede it, and being
/// generous costs one extra line of reading.
pub const HEADER_LINES: usize = 40;

/// How much of a file is read, at most.
///
/// The line cap alone is not a bound. A minified bundle is one line and several
/// megabytes, and "read the first 40 lines" would read all of it.
pub const HEADER_BYTES: usize = 8 * 1024;

/// The markers that mean "generated", in the form the tools actually emit.
///
/// `DO NOT EDIT` on its own is deliberately absent — see the module docs.
pub const MARKERS: &[&str] = &[
    // The cross-tool convention: Prettier, bazel, many codegen tools.
    "@generated",
    // Go's, which is a sentence rather than a tag.
    "Code generated by",
];

/// Whether a header names this file as generated, and which marker said so.
///
/// Returns the marker rather than a boolean so the skip reason can name it. "This
/// change was skipped" is an assertion; "skipped: every file carries `@generated`"
/// is something an operator can check.
pub fn marker_in_header(header: &str) -> Option<&'static str> {
    header.lines().take(HEADER_LINES).find_map(|line| {
        MARKERS
            .iter()
            .find(|marker| line.contains(*marker))
            .copied()
    })
}

/// Read at most a header's worth of a file.
///
/// A file that cannot be read is not generated as far as this is concerned.
/// Reviewing something unnecessarily is the safe direction; skipping a
/// hand-written file because it happened to be unreadable is not.
pub fn read_header(path: &Path) -> Option<String> {
    let file = std::fs::File::open(path).ok()?;
    let mut buffer = Vec::with_capacity(HEADER_BYTES);
    file.take(HEADER_BYTES as u64)
        .read_to_end(&mut buffer)
        .ok()?;

    // Lossy: a generated file can be any encoding, and a marker that survives
    // lossy decoding is still a marker. Refusing to look at non-UTF-8 would mean
    // reviewing every generated file with a stray byte in its licence header.
    Some(String::from_utf8_lossy(&buffer).into_owned())
}

/// Which of `paths` are generated, and by which marker.
///
/// `tree` is the materialised checkout. Paths are repository-relative.
pub fn scan(tree: &Path, paths: &[String]) -> BTreeMap<String, &'static str> {
    paths
        .iter()
        .filter_map(|path| {
            let header = read_header(&tree.join(path))?;
            let marker = marker_in_header(&header)?;
            Some((path.clone(), marker))
        })
        .collect()
}
